#!/usr/bin/env bash
#
# coverage-report.sh — render a Markdown coverage report from a Go coverage
# profile. Statement counts are read straight from the profile, so the numbers
# match `go tool cover` exactly and no second test run is needed.
#
# Usage:
#   scripts/coverage-report.sh [profile] [output]
#
#   profile   path to a coverage profile (default: coverage.out)
#   output    Markdown file to write     (default: COVERAGE.md)
#
# Examples:
#   go test ./... -coverprofile=coverage.out -covermode=atomic
#   scripts/coverage-report.sh                      # writes COVERAGE.md
#   scripts/coverage-report.sh coverage.out -       # print to stdout
set -euo pipefail

PROFILE="${1:-coverage.out}"
OUTPUT="${2:-COVERAGE.md}"

if [[ ! -f "$PROFILE" ]]; then
	echo "coverage-report: profile '$PROFILE' not found" >&2
	echo "  run: go test ./... -coverprofile=$PROFILE -covermode=atomic" >&2
	exit 1
fi

# No timestamp/commit are embedded on purpose: the report should only change —
# and therefore only be committed by CI — when coverage numbers actually move.
MODULE="$(go list -m 2>/dev/null || true)"

render() {
	awk -v module="$MODULE" '
	NR == 1 { next }                       # skip the "mode:" header line
	{
		# profile block: <path>:<l.c>,<l.c> <numStmts> <count>
		path = $1; sub(/:[0-9].*/, "", path)
		pkg  = path; sub(/\/[^\/]+$/, "", pkg)      # dir of the file = package
		total[pkg]   += $2
		gtotal       += $2
		if ($3 + 0 > 0) { covered[pkg] += $2; gcovered += $2 }
	}
	END {
		# build a sortable list of "pct\tpkg" rows
		n = 0
		for (p in total) {
			pct = (total[p] > 0) ? 100 * covered[p] / total[p] : 0
			rel = p
			if (rel == module)       rel = "(root)"
			else                     sub("^" module "/", "./", rel)
			rows[n] = sprintf("%07.3f\t%s\t%d\t%d", pct, rel, covered[p], total[p])
			n++
		}
		# simple insertion sort by pct descending (awk has no native sort)
		for (i = 1; i < n; i++) {
			key = rows[i]; j = i - 1
			while (j >= 0 && (rows[j] + 0) < (key + 0)) { rows[j+1] = rows[j]; j-- }
			rows[j+1] = key
		}

		gpct = (gtotal > 0) ? 100 * gcovered / gtotal : 0

		printf "# Test Coverage\n\n"
		printf "<!-- Generated by scripts/coverage-report.sh — do not edit by hand. -->\n\n"
		printf "**Total: %.1f%%** &nbsp;·&nbsp; %d/%d statements covered\n\n", \
			gpct, gcovered, gtotal
		printf "| Package | Coverage | |\n"
		printf "|---|---:|---|\n"
		for (i = 0; i < n; i++) {
			split(rows[i], f, "\t")
			pct = f[1] + 0; rel = f[2]
			# 20-cell bar
			filled = int(pct / 5 + 0.5); bar = ""
			for (k = 0; k < filled; k++)        bar = bar "█"
			for (k = filled; k < 20; k++)       bar = bar "░"
			printf "| `%s` | %.1f%% | `%s` |\n", rel, pct, bar
		}
		printf "\n_Coverage is measured by the `test` job in `.github/workflows/go.yml` "
		printf "and regenerated on every push to `master`._\n"
	}
	' "$PROFILE"
}

if [[ "$OUTPUT" == "-" ]]; then
	render
else
	render > "$OUTPUT"
	echo "coverage-report: wrote $OUTPUT"
fi
